#!/usr/bin/env python3
"""Generate deterministic proposed benchmark fixtures; --check never writes."""
from pathlib import Path
import argparse
import hashlib
import json
import math

ROOT = Path(__file__).resolve().parents[1]


def fixtures():
    motif = bytes.fromhex("00 00 01 01 02 02 03 03 10 20 30 40 AA 55 AA 55")
    block = bytes(32) + bytes([255]) * 32 + bytes(range(64)) + motif * 8
    assert len(block) == 256
    compression = block * 8
    state = 0x1A2B3C4D
    crypto = bytearray()
    for _ in range(2048):
        state ^= (state << 13) & 0xffffffff
        state ^= state >> 17
        state ^= (state << 5) & 0xffffffff
        state &= 0xffffffff
        crypto.append(state & 255)
    period = bytes(math.floor(128 + 100 * math.sin(2 * math.pi * n / 128) + 0.5)
                   for n in range(128))
    return {"compression": compression, "crypto": bytes(crypto), "dsp": period * 16}


def artifacts():
    values = fixtures()
    result = {}
    manifest = {
        "schema_version": 1, "input_bytes": 2048,
        "canonical_definition": "Frozen .bin and .hex files; C arrays must contain the same exact bytes.",
        "generation": {
            "compression": "[00*32 || FF*32 || 00..3F || (000001010202030310203040AA55AA55)*8]*8",
            "crypto": "xorshift32, unsigned modulo2^32, seed0x1A2B3C4D, shifts13left/17right/5left, emit lowbyte after each full update,2048updates",
            "dsp": "u[n]=floor(128+100*sin(2*pi*n/128)+0.5),n0..127; period128 repeated16times; frozen byte table is authoritative"
        }, "files": {}
    }
    header = '#ifndef BENCH_DATA_H\n#define BENCH_DATA_H\n#include <stdint.h>\n#define BENCH_INPUT_BYTES 2048u\n'
    source = '/* Generated by tools/generate_inputs.py; do not edit by hand. */\n#include "bench_data.h"\n'
    for name, data in values.items():
        assert len(data) == 2048
        lines = [" ".join(f"{v:02X}" for v in data[n:n+16]) for n in range(0, len(data), 16)]
        result[f"data/{name}.bin"] = data
        result[f"data/{name}.hex"] = ("\n".join(lines) + "\n").encode()
        manifest["files"][name] = {"bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()}
        header += f'extern const uint8_t bench_{name}_input[BENCH_INPUT_BYTES];\n'
        source += f'const uint8_t bench_{name}_input[BENCH_INPUT_BYTES] = {{\n'
        source += "\n".join("    " + ", ".join("0x" + x for x in line.split()) + "," for line in lines)
        source += '\n};\n'
    header += '#endif\n'
    result["firmware/common/include/bench_data.h"] = header.encode()
    result["firmware/common/bench_data.c"] = source.encode()
    result["data/manifest.json"] = (json.dumps(manifest, indent=2) + "\n").encode()
    config = json.loads((ROOT / "config/experiment.json").read_text(encoding="utf-8"))
    generated = '/* Generated from config/experiment.json; do not edit by hand. */\n#ifndef BENCH_CONFIG_H\n#define BENCH_CONFIG_H\n#include <stdint.h>\n'
    generated += '#if (defined(BENCH_BOARD_ESP32) + defined(BENCH_BOARD_RP2040) + defined(BENCH_BOARD_STM32)) != 1\n#error Select exactly one BENCH_BOARD target\n#endif\n'
    for index, board in enumerate(("esp32", "rp2040", "stm32")):
        generated += ('#if' if index == 0 else '#elif') + f' defined(BENCH_BOARD_{board.upper()})\n'
        counts = [config["boards"][board]["iterations"][a["name"]] for a in config["algorithms"]]
        generated += f'#define BENCH_BOARD_NAME "{board}"\n#define BENCH_EXPECTED_CPU_HZ {config["boards"][board]["target_cpu_hz"]}u\n'
        if board == "stm32":
            board_config = config["boards"][board]
            ports = {pin[1] for pin in board_config["pins_D0_to_D7"]
                     if isinstance(pin, str) and len(pin) >= 3 and pin[0] == "P"}
            if len(ports) != 1 or not ports.issubset(set("ABCDEFGHI")):
                raise ValueError("STM32 digital signals must use one GPIO port")
            generated += f'#define BENCH_SIGNAL_GPIO_PORT {ord(next(iter(ports))) - ord("A")}u\n'
            generated += f'#define BENCH_EXPECTED_OSCILLATOR_HZ {board_config["oscillator_hz"]}u\n'
        pin_names = ("RUN", "ID0", "ID1", "ID2", "ID3", "IDLE", "ERROR", "DONE")
        for name, pin in zip(pin_names, config["boards"][board]["pins_D0_to_D7"]):
            if isinstance(pin, str):
                if len(pin) < 3 or pin[0] != "P" or pin[1] not in "ABCDEFGHI" or not pin[2:].isdigit() or int(pin[2:]) > 15:
                    raise ValueError("Invalid STM32 GPIO pin")
                pin = int(pin[2:])
            if not isinstance(pin, int) or not 0 <= pin < 32:
                raise ValueError("Invalid pin index")
            generated += f'#define BENCH_PIN_{name} {pin}u\n'
        generated += 'static const uint32_t bench_iterations[12] = {' + ', '.join(str(n)+'u' for n in counts) + '};\n'
    generated += '#endif\n'
    for key in ("startup_idle_ms", "inter_algorithm_idle_ms", "post_suite_idle_ms"):
        generated += f'#define BENCH_{key.upper()} {config[key]}u\n'
    generated += '#endif\n'
    result["firmware/common/include/bench_config.h"] = generated.encode()
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for relative, data in artifacts().items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_bytes() != data:
                raise SystemExit('Generated file differs or is missing: ' + relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print('Verified' if args.check else 'Generated', len(artifacts()), 'deterministic files')


if __name__ == '__main__':
    main()
